### ISSUE TITLE
The Lockdown cogs doesnt work

### ISSUE THREAD

**Issue by MrRay70915** [Ryonez/ryo-cogs#43]
It says that only poeple with the "Administrator" role can talk when I do **[p]lockdown** but everyone is still being able to talk. How do I fix this?

**Comment by Ryonez** [comment]
The bot requires the manage_channel perm for lockdown to work.
You also need the Administrator perm for yourself.

**Comment by MrRay70915** [comment]
My bot's name is `Alpha` so thats the role it has
https://gyazo.com/7e534cd9a036a0c6fd009371733958ca

**Comment by MrRay70915** [comment]
It has the Administrator perm and all the other ones

**Comment by Ryonez** [comment]
Does it post a message when you do the command?
Please show me the channel overrides for a role when the channel is locked down.

**Comment by MrRay70915** [comment]
It works now, The channel permssions were not good

**Comment by Ryonez** [comment]
Can you please explain how they weren't good? The lockdown should be changing the overrides.

**Comment by MrRay70915** [comment]
Some roles Weren't overrding cause the role was above it

**Comment by Ryonez** [comment]
I see, thank you.
