### ISSUE TITLE
Error 404 : Unknown Emoji 

### ISSUE THREAD

**Issue by MrRay70915** [Ryonez/ryo-cogs#44]
1 more thing with `servermerge` it says that i need these to emoji's|
**hellna": "res1hellna:330424101908905990"**
**"hellyeah": "res1hellyeah:330424103259340800** 
where do I find those emojis

**Comment by Ryonez** [comment]
You won't. That code is intended to work with my bot Annabelle, who has access to them.
Servermerge should not be used, it is not intended for other bots, and should be considered unstable.

**Comment by MrRay70915** [comment]
Uhh, I have managed to get till step 5 but it gives me this error:
https://gyazo.com/8e10bf04136248bedece225d821f2c8f
