### ISSUE TITLE
I have managed to fix servermerge But it gives me an error

### ISSUE THREAD

**Issue by MrRay70915** [Ryonez/ryo-cogs#45]
Hello I'm back, I know you said it's unstable but I still wanted to give it an try, Okay so I managed to fix it, But it gives me an error at stage 5 here's the error:
https://gyazo.com/8e10bf04136248bedece225d821f2c8f

**Can you please help me fix it, Thank you.** 👍

**Comment by Ryonez** [comment]
It's not just unstable, it's not meant for other bots. And I wouldn't say you fixed it, it works as intended.
You've made changes to it from the sound of it, so I don't know what may have changed. That error shouldn't be there, and makes me think that the mservers.json is corrupt.

**Comment by MrRay70915** [comment]
I just replaced the reactions
